Repository scheduleonce/ng-strictify, pull requests merged in 2022-05, with the labels that each got.

#21 fixed pr
  .lighthouse/jenkins-x/pullrequest.yaml
Labels: approved, size/M

#26 code updated
  deploy.sh
Labels: approved

#27 updated code to execute inside builder folder
  deploy.sh
Labels: approved, size/XS

#29 updating code to check the execution point in release pipeline
  builder/package-lock.json
  builder/package.json
  deploy.sh
Labels: approved, size/S

#30 updated steps to login
  deploy.sh
Labels: approved, size/XS

#31 path updated
  deploy.sh
Labels: approved, size/XS

#32 updating code to publish package
  .gitignore
  builder/package-lock.json
  builder/package.json
  deploy.sh
Labels: approved, size/S

#33 removing variable not in use
  deploy.sh
Labels: approved, size/XS

#34 updated destination path
  builder/package.json
Labels: approved, size/XS

#35 relogin for checking issue
  deploy.sh
Labels: approved, size/XS

#36 updating code to create .npmrc file at runtime inside builder folder
  builder/package-lock.json
  builder/package.json
  deploy.sh
  package-deploy/npm-login.js
Labels: approved, size/M

#38 [Master] ONCEHUB-51490: updated the change log file and used the ng-strictify version in test-app for fixing the vulnerability
  CHANGELOG.md
  builder/package-lock.json
  builder/package.json
  test-app/package-lock.json
  test-app/package.json
Labels: size/L, approved

#39 Update README.md
  README.md
Labels: approved, size/XS
