Repository scheduleonce/ng-strictify, pull requests merged in 2024-02, with the labels that each got.

#66 [FIXED] vulnerability found in package ip [TEAM PR]
  test-app/angular.json
  test-app/package-lock.json
  test-app/package.json
  test-app/tsconfig.json
Labels: size/XXL

#67 [FIXED] vulnerability found in package ip [APP3 PR]
  test-app/angular.json
  test-app/package-lock.json
  test-app/package.json
  test-app/tsconfig.json
Labels: approved, size/XXL

#69 Merging staging-app2 in to master.
  CHANGELOG.md
  builder/package-lock.json
  builder/package.json
  test-app/angular.json
  test-app/package-lock.json
  test-app/package.json
  test-app/tsconfig.json
Labels: approved, size/XXL

#70 [fixed] vulnerability found in package @angular/core [MASTER PR]
  CHANGELOG.md
  builder/package-lock.json
  builder/package.json
  test-app/package-lock.json
  test-app/package.json
Labels: size/L, approved
